# Generated by Django 4.2.6 on 2023-11-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('carrera', models.CharField(max_length=25)),
                ('votos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField()),
                ('comentario', models.CharField(max_length=200)),
                ('tutor_valoraciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tutor')),
                ('usuario_valoraciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='usuario_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=1000)),
                ('votos', models.IntegerField()),
                ('pregunta_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pregunta')),
                ('usuario_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='usuario_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=45, null=True)),
                ('titulo', models.CharField(max_length=45)),
                ('archivo', models.FileField(upload_to='uploads/')),
                ('categorias', models.CharField(max_length=45)),
                ('usuario_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
    ]
