# Generated by Django 4.2.6 on 2023-10-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Carrera', models.CharField(max_length=25)),
                ('Votos', models.IntegerField()),
            ],
        ),
    ]
