# Generated by Django 4.2.6 on 2023-11-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Es_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
